CREATE TABLE agencies (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(190) NOT NULL,slug VARCHAR(190) UNIQUE NOT NULL,phone VARCHAR(80),whatsapp_number VARCHAR(80),logo_path VARCHAR(255),address TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE cars (id INT AUTO_INCREMENT PRIMARY KEY,agency_id INT NOT NULL,name VARCHAR(190) NOT NULL,slug VARCHAR(220) UNIQUE NOT NULL,category VARCHAR(80) NOT NULL,transmission VARCHAR(80) NOT NULL,fuel_type VARCHAR(80) NOT NULL,seats INT DEFAULT 5,price_per_day DECIMAL(10,2) NOT NULL,image_path VARCHAR(255),description TEXT,features TEXT,deposit_info TEXT,documents_required TEXT,insurance_info TEXT,status ENUM('available','rented','maintenance','hidden') DEFAULT 'available',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE cities (id INT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(190) UNIQUE NOT NULL,name VARCHAR(190) NOT NULL,seo_title VARCHAR(255) NOT NULL,seo_description VARCHAR(255) NOT NULL,h1 VARCHAR(255) NOT NULL,intro_text TEXT NOT NULL,pickup_points TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE leads (id INT AUTO_INCREMENT PRIMARY KEY,car_id INT NOT NULL,agency_id INT NOT NULL,full_name VARCHAR(190) NOT NULL,phone VARCHAR(80) NOT NULL,pickup_city VARCHAR(190) NOT NULL,pickup_location VARCHAR(190) NOT NULL,pickup_date DATE NOT NULL,return_date DATE NOT NULL,message TEXT,whatsapp_opened TINYINT(1) DEFAULT 0,status ENUM('new','contacted','confirmed','cancelled') DEFAULT 'new',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE admins (id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(190) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO agencies (name,slug,phone,whatsapp_number,address) VALUES ('Atlas Drive System','atlas-drive-system','+212 600 000 000','212600000000','Casablanca, Maroc');
INSERT INTO admins (username,password_hash) VALUES ('admin','$2y$12$iA1JNCyaPr4qtpYR5rJMbeRciK52fVLKAYidh1l4HrEHb1rfInZ/G');
INSERT INTO cities (slug,name,seo_title,seo_description,h1,intro_text,pickup_points) VALUES
('casablanca','Casablanca','Location voiture Casablanca | Atlas Drive System','Voiture à louer à Casablanca avec livraison aéroport Mohammed V et confirmation WhatsApp.','Location de voiture à Casablanca','Casablanca demande une flotte flexible: trajets d’affaires à Maârif, arrivées tardives à Mohammed V et rendez-vous entre Casa-Port et Anfa. Atlas Drive System met en avant une réservation rapide avec conditions visibles avant confirmation.','Aéroport Mohammed V, Maârif, Casa Voyageurs, Casa-Port, Anfa'),
('marrakech','Marrakech','Location voiture Marrakech | Atlas Drive System','Location voiture Marrakech Menara, Guéliz, Hivernage et Médina avec WhatsApp.','Location de voiture à Marrakech','À Marrakech, les clients alternent souvent entre hôtel, riad, excursions et arrivée à Menara. Cette page privilégie les prises en charge pratiques et les véhicules adaptés aux routes vers l’Ourika, Essaouira ou le centre-ville.','Aéroport Marrakech Menara, Guéliz, Hivernage, Médina'),
('agadir','Agadir','Location voiture Agadir | Atlas Drive System','Louez une voiture à Agadir, Taghazout ou aéroport Al Massira avec conditions transparentes.','Location de voiture à Agadir','Agadir exige une expérience simple pour plage, marina, Taghazout et déplacements depuis Al Massira. Les demandes sont capturées avant WhatsApp pour aider l’agence à suivre chaque prospect sans perdre les conversations.','Aéroport Agadir Al Massira, Marina, Centre-ville, Taghazout');
INSERT INTO cars (agency_id,name,slug,category,transmission,fuel_type,seats,price_per_day,description,features,deposit_info,documents_required,insurance_info,status) VALUES
(1,'Dacia Logan Diesel Manuelle','dacia-logan-diesel-manuelle','Economique','Manuelle','Diesel',5,250,'Berline économique fiable pour ville et longs trajets au Maroc.','Climatisation, Bluetooth, coffre familial','Caution par empreinte TPE non débitée ou chèque de garantie restitué lors du retour du véhicule.','Permis de conduire, CIN ou passeport.','Assurance standard avec franchise expliquée.','available'),
(1,'Dacia Duster Diesel','dacia-duster-diesel','SUV','Manuelle','Diesel',5,420,'SUV robuste pour routes urbaines, aéroport et escapades.','Climatisation, garde au sol élevée, caméra selon disponibilité','Caution transparente selon durée et profil.','Permis de conduire, CIN ou passeport.','Assurance incluse selon contrat.','available'),
(1,'Renault Clio 5 Essence','renault-clio-5-essence','Compacte','Manuelle','Essence',5,330,'Compacte moderne et agile pour Casablanca ou Marrakech.','Écran tactile, climatisation, faible consommation','Empreinte ou chèque non encaissé.','Permis de conduire, CIN ou passeport.','Assurance standard.','available'),
(1,'Hyundai Accent Diesel','hyundai-accent-diesel','Economique','Manuelle','Diesel',5,310,'Confort diesel pour familles et professionnels.','Climatisation, grand coffre, USB','Caution transparente.','Permis de conduire, CIN ou passeport.','Assurance incluse.','available'),
(1,'Peugeot 208 Automatique','peugeot-208-automatique','Compacte','Automatique','Essence',5,450,'Citadine premium automatique pour conduite fluide.','Boîte automatique, climatisation, aide au stationnement','Caution adaptée au véhicule.','Permis de conduire, CIN ou passeport.','Assurance standard avec franchise.','available'),
(1,'Volkswagen Golf 8 Automatique','volkswagen-golf-8-automatique','Compacte','Automatique','Diesel',5,650,'Compacte haut de gamme pour clients exigeants.','Digital cockpit, automatique, confort premium','Caution véhicule premium expliquée avant confirmation.','Permis de conduire, CIN ou passeport.','Assurance incluse.','available'),
(1,'Hyundai Tucson SUV','hyundai-tucson-suv','SUV','Automatique','Diesel',5,780,'SUV confortable pour routes, famille et bagages.','Automatique, climatisation bizone, grand coffre','Caution transparente.','Permis de conduire, CIN ou passeport.','Assurance selon contrat.','available'),
(1,'Range Rover Evoque Luxe','range-rover-evoque-luxe','Luxe','Automatique','Diesel',5,1400,'SUV luxe pour rendez-vous premium, hôtel et aéroport.','Finition luxe, automatique, caméra, cuir','Caution luxe par empreinte ou garantie validée.','Permis, passeport/CIN et validation profil.','Assurance premium avec franchise.','available');
